[package]
name = "ommatidia"
description = "Neural frame reconstruction from sparse samples"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
keywords = ["graphics", "upscaling", "neural"]
categories = ["rendering"]

[dependencies]
blade-graphics.workspace = true
blade-macros = "0.3"
bytemuck.workspace = true
half.workspace = true
log.workspace = true
meganeura.workspace = true
ron.workspace = true
serde.workspace = true

[dev-dependencies]
naga = { workspace = true }
